### ISSUE TITLE
Unable to create input format org.apache.hadoop.mapred.TextInputFormat error

### ISSUE THREAD

**Issue by nakhanha** [hdinsight/presto-hdinsight#13]
sudo presto --debug --schema default --execute 'select count(*) from PrestoHiveSampleTable'

Query 20180614_222037_00005_wksty failed: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
com.facebook.presto.spi.PrestoException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
        at com.facebook.presto.hive.HiveSplitSource.propagatePrestoException(HiveSplitSource.java:139)
        at com.facebook.presto.hive.HiveSplitSource.isFinished(HiveSplitSource.java:117)
        at com.facebook.presto.split.ConnectorAwareSplitSource.isFinished(ConnectorAwareSplitSource.java:72)
        at com.facebook.presto.split.BufferingSplitSource.isFinished(BufferingSplitSource.java:86)
        at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:89)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:354)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat

**Comment by nakhanha** [comment]
I see that presto-server files are downloaded and used in createslider.sh but createslider.sh is never called.
